import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
const A='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002',C='00000000-0000-0000-0000-000000000003';
const X='10000000-0000-0000-0000-000000000001',Y='10000000-0000-0000-0000-000000000002';
test('spec integration: PIN recovery, member catalog, conditions, reservations, completion and expiration',async()=>{
 const db=new PGlite({extensions:{pgcrypto}});
 const bootstrap=readFileSync('tests/beta2.test.js','utf8').match(/await db.exec\(`([\s\S]*?)`\);/)[1].replaceAll('${A}',A).replaceAll('${B}',B).replaceAll('${C}',C);
 const user=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 const login=async(nickname,pin='1234',register=false)=>(await db.query('select poca3_login($1,$2,$3) as data',[nickname,pin,register])).rows[0].data;
 const state=async()=>(await db.query('select poca3_state() as data')).rows[0].data;
 const act=async(action,input={})=>(await db.query('select poca3_action($1,$2::jsonb) as data',[action,JSON.stringify(input)])).rows[0].data;
 const publish=async(id,target,qty=2)=>act('publish',{give:[{id,qty}],conditions:{[id]:{ids:[target],members:[],any:false}},revision:(await state()).me.revision});
 try{
 await db.exec(bootstrap);await db.exec('create schema extensions');
 for(const file of ['supabase/schema.sql','supabase/migrations/002_shared_catalog.sql','supabase/migrations/003_spec.sql','supabase/migrations/004_member_catalog.sql','supabase/migrations/005_catalog_edit.sql','supabase/migrations/006_reset_selections.sql','supabase/migrations/007_chat.sql','supabase/migrations/008_signup_device.sql','supabase/migrations/009_login_wait.sql','supabase/migrations/010_remove_login_cooldown.sql','supabase/migrations/011_next_features.sql','supabase/migrations/012_admin_participants.sql','supabase/migrations/013_session_management.sql'])await db.exec(readFileSync(file,'utf8'));
 await user(A);assert.equal((await state()).account,null);await assert.rejects(()=>act('join',{}));
 assert.ok((await login('A','1234',true)).account);await act('join',{day:'2026-09-18',region:'서울'});await publish(X,Y);
 await assert.rejects(()=>db.query('select poca2_action($1,$2)',['leave',{}]));await assert.rejects(()=>db.query('select * from poca3_accounts'));
 await assert.rejects(()=>act('catalog_add',{}));
 await user(B);await login('B','1234',true);await act('join',{day:'2026-09-18',region:'부산'});let s=await publish(Y,X);assert.equal(s.matches.length,0);assert.equal(s.listings.length,0);assert.equal(s.count,1);
 await assert.rejects(()=>act('request',{peerId:A,giveId:Y,receiveId:X}));
 await assert.rejects(()=>act('join',{day:'2026-09-18',region:'서울'}));
 await act('leave');await act('join',{day:'2026-09-18',region:' 서울 '} );s=await publish(Y,X);assert.equal(s.matches[0].mutual,true);assert.equal(s.count,2);assert.equal(s.me.region,'서울');assert.ok(s.regions.includes('부산'));

 s=await act('request',{peerId:A,giveId:Y,receiveId:X});let t=s.trades[0];assert.equal(t.status,'awaiting');await assert.rejects(()=>act('accept',{id:t.id}));
 await user(A);await act('accept',{id:t.id});const originalExpiry=t.expiresAt;
 s=await act('extend',{id:t.id});assert.equal(new Date(s.trades[0].expiresAt)-new Date(originalExpiry),900000);assert.equal(s.trades[0].extended,true);
 await user(C);await assert.rejects(()=>act('extend',{id:t.id}));await user(B);await assert.rejects(()=>act('extend',{id:t.id}));
 await user(A);s=await act('complete',{id:t.id});assert.equal(s.me.give[0].qty,1);assert.equal(s.trades[0].status,'completed');await assert.rejects(()=>act('complete',{id:t.id}));
 await user(B);s=await state();assert.equal(s.me.give[0].qty,1);assert.equal(s.trades[0].status,'completed');await assert.rejects(()=>act('confirm',{id:t.id}));
 await user(C);assert.ok((await login('A','9999')).error);s=await login('A');assert.equal(s.account.id,A);assert.equal(s.me.give[0].qty,1);assert.equal(s.trades[0].status,'completed');assert.equal((await db.query('select auth.uid() as id')).rows[0].id,C);
 s=await act('request',{peerId:B,giveId:X,receiveId:Y});t=s.trades.find(t=>t.status==='awaiting');assert.ok(t);assert.equal(s.matches.length,0);
 await db.exec("reset role; update poca2_trades set expires_at=now()-interval '1 second' where status='awaiting'");await user(C);s=await state();assert.equal(s.matches.length,1);assert.equal(s.trades.filter(t=>t.status==='awaiting').length,0);
 await user(C);await db.query("insert into storage.objects(bucket_id,name) values('poca-photos',$1)",[C+'/unit.jpg']);
 s=await act('catalog_add',{img:C+'/unit.jpg',name:'유닛 A',event:'팬미팅',kind:'MD',release:'새 발매',members:['원이','제나']});assert.deepEqual(s.catalog.find(c=>c.name==='유닛 A').members,['원이','제나']);assert.equal(s.catalog.find(c=>c.name==='유닛 A').release,'새 발매');

 const chat=async(action,input={})=>(await db.query('select poca_chat($1,$2::jsonb) as data',[action,JSON.stringify(input)])).rows[0].data;
 const manage=async(operation,input)=>(await db.query('select poca_catalog_manage($1,$2::jsonb) as data',[operation,JSON.stringify(input)])).rows[0].data;
 const room=await chat('open',{peerId:B,giveId:X,receiveId:Y});
 const messageId='90000000-0000-0000-0000-000000000001';
 await chat('send',{id:room.id,messageId,body:'입구 <안내> 앞'});await chat('send',{id:room.id,messageId,body:'입구 <안내> 앞'});
 assert.equal((await chat('messages',{id:room.id})).messages.length,1);
 await user(B);assert.equal((await chat('list')).rooms[0].unread,1);const received=await chat('messages',{id:room.id});await chat('read',{id:room.id,through:received.messages[0].seq});assert.equal((await chat('list')).rooms[0].unread,0);
 const D='00000000-0000-0000-0000-000000000004';await db.exec(`reset role;insert into auth.users values('${D}')`);await user(D);await login('D','1234',true);
 assert.equal((await chat('list')).rooms.length,0);await assert.rejects(()=>chat('messages',{id:room.id}));await assert.rejects(()=>chat('send',{id:room.id,messageId:'90000000-0000-0000-0000-000000000002',body:'침입'}));await assert.rejects(()=>db.query('select * from poca_messages'));
 await user(C);s=await manage('edit',{id:X,name:'수정 포카',event:'수정 행사',release:'수정 발매',kind:'MD',members:['원이'],img:'images/poca_01.jpg'});assert.equal(s.me.give[0].name,'수정 포카');assert.equal(s.me.give[0].release,'수정 발매');assert.equal(s.trades.find(t=>t.status==='completed').give.name,'포카 2');
 s=await manage('delete',{id:X});assert.ok(!s.catalog.some(c=>c.id===X));assert.equal(s.me.give.length,0);assert.ok(s.trades.some(t=>t.status==='completed'));
 s=await manage('restore',{id:X});assert.ok(s.catalog.some(c=>c.id===X));await publish(X,Y);
 s=(await db.query('select poca_reset_selections($1,$2) as data',['want',(await state()).me.revision])).rows[0].data;assert.equal(s.me.give[0].qty,2);assert.deepEqual(s.me.conditions,{});
 s=(await db.query('select poca_reset_selections($1,$2) as data',['give',s.me.revision])).rows[0].data;assert.equal(s.me.give.length,0);assert.ok(s.trades.some(t=>t.status==='completed'));
 await publish(X,Y,1);await user(B);await publish(Y,X,1);s=await act('request',{peerId:A,giveId:Y,receiveId:X});const last=s.trades.find(t=>t.status==='awaiting');await user(C);await act('accept',{id:last.id});s=await act('complete',{id:last.id});assert.deepEqual(s.me.give,[]);await user(B);assert.deepEqual((await state()).me.give,[]);await assert.rejects(()=>act('complete',{id:last.id}));await user(C);
 await act('leave');await act('logout');assert.equal((await state()).account,null);s=await login('A');assert.equal(s.trades[0].status,'completed');
 await user(A);await act('logout');
 assert.equal((await login('새가입','1234',true)).code,'DEVICE_ACCOUNT_EXISTS');
 assert.equal((await login('B','1234',true)).code,undefined);
 assert.equal((await login('A')).account.id,A);
 assert.equal((await state()).trades[0].status,'completed');
 await user(C);await act('logout');assert.ok((await login('새가입','1234',true)).account);
 assert.equal((await login('A')).account.id,A);
 await assert.rejects(()=>db.query('select poca_admin_participants()'));
 await db.exec(`reset role;insert into poca3_admins values('${A}')`);await user(C);
 const roster=(await db.query('select poca_admin_participants() as data')).rows[0].data;assert.ok(roster.some(p=>p.nickname==='B'));assert.ok(roster.every(p=>Object.keys(p).sort().join(',')==='devices,expiresAt,id,nickname'));
 await user(B);await assert.rejects(()=>db.query('select poca_admin_participants()'));await user(C);
 for(let i=0;i<8;i++)assert.match((await login('A','0000')).error,/닉네임 또는 PIN/);
 assert.equal((await login('A')).account.id,A);
 await db.exec("reset role;insert into poca3_login_limits(key,failures,blocked_until) values('a',5,now()+interval '15 minutes') on conflict(key) do update set blocked_until=excluded.blocked_until");await user(C);
 assert.equal((await login('A')).account.id,A);
 assert.match((await login('A','0000')).error,/닉네임 또는 PIN/);
 s=await login('A');const remaining=Date.parse(s.sessionExpiresAt)-Date.now();assert.ok(remaining>3500000 && remaining<=3600000);assert.equal((await state()).sessionExpiresAt,s.sessionExpiresAt);
 await user(B);await assert.rejects(()=>db.query('select poca_admin_logout($1)',[A]));await user(C);await assert.rejects(()=>db.query('select poca_admin_logout($1)',[A]));
 await db.query('select poca_admin_logout($1)',[B]);await user(B);assert.equal((await state()).account,null);await assert.rejects(()=>act('publish',{}));assert.equal((await login('B')).account.id,B);
 await user(C);await db.exec(`reset role;update poca3_sessions set expires_at=now()-interval '1 second' where device='${C}'`);await user(C);assert.equal((await state()).account,null);await assert.rejects(()=>db.query('select poca_admin_participants()'));assert.ok((await login('A')).trades.some(t=>t.status==='completed'));
 }finally{await db.close();}
});
